---
title: Final Projects
---

For your final assignment in 140.712.01 Advanced Data Science II, you will work on a month-long data science project. The goal of the project is to go through the complete data science process to answer questions you have about some topic of your own choosing. You will acquire the data, design your visualizations, run statistical analysis, and communicate the results.

### Project Team
You may work individually or in a team. If working alone, you are still expected to complete all parts of the project (described below). If part of a team, you will work closely with other classmates (a maximum of 3 students per team) on this project. You can come up with your own teams and use Slack to find prospective team members. In general, we do not anticipate that the grades for each group member will be different. However, we reserve the right to assign different grades to each group member based on peer assessments (see below).

### Project Milestones
There are a few milestones for your final project. **It is critical to note that no extensions will be given for any of the project due dates for any reason. Late days may not be used.** Projects submitted after the final due date will not be graded. If you anticipate any issues (e.g., due to business travel) you need to send an email to the teaching staff **at least one week in advance**.

| Date       | Description |
| ------------- |-------------|
| November 9 by 11:59pm | Form a team and submit a project proposal |
| November 12 - 16 | Project review meeting with TA or Instructor |
| December 14 by 11:59pm | RMarkdown and compiled HTML due |
| December 14 by 11:59pm | Project webpage and screencast due |
| December 16 by 11:59pm | Peer assessment due |
| December 17, 19 | Final project presentations, project screencasts shown | 

## Deliverables
There are several deliverables for your project that will be graded individually to make up your final project score.

### Team Registration and Proposal
You start by filling out this google form to define your teams and project proposal. [This form](https://goo.gl/forms/roN22gSaVjHe5vp53) should be filled out by Friday November 9, 2018 at 11:59pm. The title can be changed at a later date. Each team (or individual if working alone) will only need to submit one form. Based on your proposals, a TA will be assigned to your team who will guide you through the rest of the project. You will schedule a project review meeting with your TA or Instructor the following week. Make sure all of your team members are present at the meeting.

### RMarkdown and HTML Files
An important part of your project is the RMarkdown and HTML files. This will detail your steps in developing your solution, including how you collected the data, alternative solutions you tried, describing statistical methods you used, and the insights you got. Equally important to your final results is how you got there! Your RMarkdown and HTML files are the place you describe and document the space of possibilities you explored at each step of your project. We strongly advise you to include many visualizations.

Your RMarkdown should include the following topics. Depending on your project type, the amount of discussion you devote to each of them will vary:

* **Motivation and Overview**: Provide an overview of the project goals and the motivation for it. Consider that this will be read by people who did not see your project proposal.

* **Related Work**: Anything that inspired you, such as a paper, a web site, or something we discussed in class.

* **Initial Questions**: What questions are you trying to answer? How did these questions evolve over the course of the project? What new questions did you consider in the course of your analysis?

* **Data**: What is the data source? Document the data import, wrangling, etc.

* **Exploratory Data Analysis**: What visualizations did you use to look at your data in different ways? What are the different statistical methods you considered? Justify the decisions you made, and show any major changes to your ideas. How did you reach these conclusions? You should use this section to motivate the statistical analyses that you decided to use in the next section. 

* **Data Analysis**: What statistical or computational method did you apply and why? What others did you consider? 

* **Narrative and Summary**: What did you learn about the data? How did you answer the questions? How can you justify your answers? What are the limitations of the analyses? 

As this will be your only chance to describe your project in detail, make sure that your RMarkdown file and compiled HTML file are standalone documents that fully describe your process and results. The RMarkdown and HTML files are due Friday, December 14 by 11:59pm. For instructions on how to submit, please see **Submission Instructions** below.

### Code
We expect you to write high-quality and readable R code in your RMarkdown file. You should strive for doing things the right way and think about aspects such as reproducibility and writing efficient code. We also expect you to document your code.

### Project Website
You will create a public website for your project (e.g. Github Pages or any other web hosting service of your choice). The web site should effectively summarize the main results of your project and tell a story. Consider your audience (the site is public) and keep the level of discussion at the appropriate level. Your RMarkdown file, HTML file and data should be linked from your GitHub Repository (see below) to the web site as well. Also embed your main visualizations and your screencast in your website.

The final project website is due Friday, December 14 by 11:59pm. For instructions on how to submit, please see Submission Instructions below.


### Project Screencast
Each team will create a **two minute screencast with narration** showing a demo of your project and/or some slides. Information about how to prepare these screencasts can be found [here](https://docs.google.com/document/d/1alPLuBOW5YPoQDa57KZes1h72PoQDoDj21-UEKOHp1I/pub). Please make sure that the sound quality of your video is good. Upload the video to an online video-platform such as YouTube or Vimeo and embed it into your project web page. You will show your team's video in class.

We will **strictly enforce the two minute time limit for the video**, so please make sure you are not running longer. Use principles of good storytelling and presentations to get your key points across. Focus the majority of your screencast on your main contributions rather than on technical details. What do you feel is the best part of your project? What insights did you gain? What is the single most important thing you would like your audience to take away? Make sure it is upfront and center rather than at the end.

The final project screencast is due Friday, December 14 by 11:59pm. For instructions on how to submit, please see Submission Instructions below.

### Peer Assessment
It is important to provide positive feedback to people who truly worked hard for the good of the team and to also make suggestions to those you perceived not to be working as effectively on team tasks. We ask you to provide an honest assessment of the contributions of the members of your team, including yourself. The feedback you provide should reflect your judgment of each team member:

* **Preparation**: Were they prepared during team meetings?

* **Contribution**: Did they contribute productively to the team discussion and work?

* **Respect for others' ideas**: Did they encourage others to contribute their ideas?

* **Flexibility**: Were they flexible when disagreements occurred?

Your teammates' assessment of your contributions and the accuracy of your self-assessment will be considered as part of your overall project score. The peer assessment is due Sunday, December 16 by 11:59pm. For instructions on how to submit, please see **Submission Instructions** below.


## Submission Instructions
#### How to submit RMarkdown, HTML files, Website and Screencast (due Friday, December 14)
1. Create a GitHub repository which should include the data used for the final project, the RMarkdown file and the compiled HTML file. If the data are too big to fit in the repository, make the data accessible somewhere online (google drive, downloadable link, etc). Inside the RMarkdown file at the top, include instructions on where to access the data. If we cannot access your work or links because these directions are not followed correctly, we will not grade your work.
2. You should only have one GitHub repository per team, but make sure the names of all group members are inside the RMarkdown file at the top.
3. Fill out this [google form to submit the links to the website and screencast](https://goo.gl/forms/oVkH1XUhCUt86f6J2). **If we cannot access the website or screencast, we cannot grade it**. The website should include a description and links to accessing the data and location of your GitHub repository. 

#### How to submit the Peer Assessment (due Sunday, December 16)
Each individual team member needs to fill out this [google form for the peer evaluation](https://goo.gl/forms/3yKf3liLdpKcINHH3). Your individual project score will take into account your self and peer assessment.


## Grading
The final project will be graded in three amin parts: 

1. **Project proposal and team meeting** (10%). This portion represents the Team Registration, Final Project Proposal and meeting with your assigned TA or Instructor.
2. **Data Analysis** (50%). This portion will be based on your RMarkdown and HTML files in your GitHub repository. This includes the quality of your data analysis and R code, the complexity and level of difficulty of your project, completeness and overall functionality of your analysis.
3. **Website** (20%), **Youtube video** (10%) and **Final Project Presentation** (10%). This portion will based on the quality of your storytelling and summarization aspects. 

Your individual project score will also be modified by your peer evaluations.

## Example Final Projects

Here are some examples of successful final projects. **Note**: These projects came from previous courses we taught on Data Science similar to this one, except the sometimes the courses used Python, not R.

1. **Predicting Hubway bike/dock availability** ([Website](http://cs109hubway.github.io/classp/), [Screencast](https://www.youtube.com/watch?v=2wK8jpNMjXI))
2. **I want to believe: An exploratory and predictive analysis of crowd-sourced UFO sightings** ([Website](http://ama7278.wixsite.com/ufos), [Screencast](https://youtu.be/VeHm2auz1lE))
3. **Predicting Healthcare Cost Among Medicare Beneficiaries in Massachusetts** ([Website](http://xiner-shirley-paula.github.io/DataScienceFinalProject/), [Screencast](https://www.youtube.com/watch?v=_vj-e62mPkw))
4. **Branding -- Insights on Brand in Marketing** ([Website](http://whalexyz.github.io/BIO260Project/), [Screencast](https://www.youtube.com/watch?v=YjggPri5FsQ))
5. **Across the Bay 10K Race** ([Website](https://sites.google.com/site/atb10kbridgerace/home), [Screencast](https://sites.google.com/site/atb10kbridgerace/home/screencast))
6. **Predicting Citation Counts of arXiv Papers** ([Website](https://sites.google.com/site/teamcitations/), [Screencast](https://www.youtube.com/watch?v=bjAcHu8JRG0))
7. **Improving University Energy Efficiency: Building Energy Demand Prediction** ([Website](http://cs109-energy.github.io/), [Screencast](https://www.youtube.com/watch?v=JiAQxctOntQ))
8. **Predicting AirBnb Success** ([Website](http://hamelsmu.github.io/AirbnbScrape/), [Screencast](https://www.youtube.com/watch?v=raGjUj5qArc))
